name: SharedWeblatePush

# SPDX-FileCopyrightText: 2026 Sangoma US Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

# This workflow should be executed upon push to a weblate/x branch.
# It makes a new PR and then lints the push.

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write
  statuses: write

env:
  # These values should match your version numbers and grow with you.
  WEBLATE_BRANCH: ${{ endsWith(github.ref,'/16.0') && 'weblate/16.0' ||
                      endsWith(github.ref,'/17.0') && 'weblate/17.0' ||
                      endsWith(github.ref,'/18.0') && 'weblate/18.0' ||
                      'weblate/0' }}
  # The release/x numbering is nearly the same as the weblate/x numbering.
  RELEASE_BRANCH: ${{ endsWith(github.ref,'/16.0') && 'release/16.0' ||
                      endsWith(github.ref,'/17.0') && 'release/17.0' ||
                      endsWith(github.ref,'/18.0') && 'release/18.0' ||
                      'release/0' }}
    
jobs:
  MakePR:
    name: Auto make PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    concurrency:
      group: check-shared-weblate-push-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout full
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout weblate/x branch
        run: git checkout "${WEBLATE_BRANCH}"

      - name: Make Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh pr create \
            --head="${WEBLATE_BRANCH}" \
            --base="${RELEASE_BRANCH}" \
            --title="Pulling ${WEBLATE_BRANCH} into ${RELEASE_BRANCH}" \
            --body="An automated PR that was generated by a push to a weblate branch. If it fails to merge automatically to the corresponding release branch, then check for failures carefully before manually merging, e.g., linting issues, changes outside i18n directory, etc."

      - name: Super-linter slim validation only
        uses: super-linter/super-linter/slim@v8.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
